services:
  portal-server:
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: /target/portal-nordsy-spb-0.0.1-SNAPSHOT.jar
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: always