spring.application.name=portal-nordsy-spb

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/portal
spring.datasource.url=jdbc:postgresql://localhost:5450/portal
spring.datasource.username=portal
spring.datasource.password=portalnew
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.app.jwtExpirationMs=3000000
spring.app.SECRET_KEY=BF7FD11ACE545745B7BA1AF98B6F156D127BC7BB544BAB6A4FD74E4FC7