create table area5s
(
    id            bigint generated by default as identity
        primary key,
    name          varchar(255),
    department_id bigint
        constraint fkfef2aaj9aqjhc7s07g7g3q5cl
            references department5s
);

alter table area5s
    owner to portal;

