create table area
(
    id            bigint generated by default as identity
        primary key,
    name          varchar(255),
    department_id bigint
        constraint fkict716pjemenn3hagjn7ifehv
            references department
);

alter table area
    owner to portal;

