create table post
(
    id          bigint generated by default as identity
        primary key,
    description text,
    title       varchar(255),
    chapter_id  bigint
        constraint fksu4ha2yjk3v6ywrkw32lmj9ce
            references chapter
);

alter table post
    owner to portal;

